"""
Professional PDF clinical report generator for SonoClarity.
Uses fpdf2 to create a formatted PDF with patient info, annotated image, 
clinical measurements table, and recommendation.
"""
import os
import tempfile
import datetime
import cv2
from fpdf import FPDF


class UltrasoundReport(FPDF):
    """Custom PDF class with header/footer branding."""
    
    LAVENDER = (123, 94, 167)      # #7B5EA7
    SAGE_GREEN = (156, 175, 136)   # #9CAF88
    ERROR_ROSE = (180, 100, 80)    # Dusty rose / warning
    DARK_TEXT = (40, 40, 40)
    LIGHT_TEXT = (120, 120, 120)
    
    def header(self):
        # Lavender accent bar at top
        self.set_fill_color(*self.LAVENDER)
        self.rect(0, 0, 210, 4, 'F')
        
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(*self.LAVENDER)
        self.set_y(12)
        self.cell(0, 10, "SonoClarity Medical Report", ln=True, align="C")
        
        # Timestamp
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self.LIGHT_TEXT)
        now = datetime.datetime.now().strftime("%B %d, %Y at %I:%M %p")
        self.cell(0, 5, f"Generated: {now}", ln=True, align="C")
        
        self.ln(5)
    
    def footer(self):
        self.set_y(-25)
        # Separator line
        self.set_draw_color(*self.LAVENDER)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(3)
        
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*self.LIGHT_TEXT)
        self.multi_cell(0, 3.5,
            "DISCLAIMER: This report is generated by an AI-assisted computer-aided detection tool and is intended "
            "for research and educational purposes only. It does not constitute a medical diagnosis. Always consult "
            "a qualified healthcare professional for clinical interpretation and treatment decisions.",
            align="C"
        )
        self.set_font("Helvetica", "", 7)
        self.cell(0, 4, f"Page {self.page_no()}", align="C")


def generate_pdf_report(vis_img, results_list, meta, output_path):
    """
    Generate a professional PDF clinical report.
    
    Args:
        vis_img:        Annotated BGR numpy array from the analyzer
        results_list:   List of result dicts (from analyzer)
        meta:           Dict with keys: image_path, age, site
        output_path:    Where to save the PDF
    
    Returns:
        (success: bool, message: str)
    """
    try:
        pdf = UltrasoundReport(orientation="P", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=30)
        pdf.add_page()
        
        # ── Patient Information Section ──
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*UltrasoundReport.DARK_TEXT)
        pdf.cell(0, 8, "Patient Information", ln=True)
        
        pdf.set_draw_color(*UltrasoundReport.LAVENDER)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        
        pdf.set_font("Helvetica", "", 10)
        age_val = meta.get("age", "N/A")
        site_val = meta.get("site", "N/A")
        
        # Two-column patient info
        pdf.set_text_color(*UltrasoundReport.LIGHT_TEXT)
        pdf.cell(30, 6, "Patient Age:", ln=False)
        pdf.set_text_color(*UltrasoundReport.DARK_TEXT)
        pdf.cell(55, 6, f"{int(age_val)} years" if age_val else "N/A", ln=False)
        
        pdf.set_text_color(*UltrasoundReport.LIGHT_TEXT)
        pdf.cell(30, 6, "Exam Site:", ln=False)
        pdf.set_text_color(*UltrasoundReport.DARK_TEXT)
        pdf.cell(55, 6, str(site_val), ln=True)
        
        pdf.set_text_color(*UltrasoundReport.LIGHT_TEXT)
        pdf.cell(30, 6, "Source Image:", ln=False)
        pdf.set_text_color(*UltrasoundReport.DARK_TEXT)
        img_name = os.path.basename(meta.get("image_path", "Unknown"))
        pdf.cell(0, 6, img_name, ln=True)
        
        pdf.ln(5)
        
        # ── Annotated Ultrasound Image ──
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*UltrasoundReport.DARK_TEXT)
        pdf.cell(0, 8, "Annotated Ultrasound Image", ln=True)
        
        pdf.set_draw_color(*UltrasoundReport.LAVENDER)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        
        # Save vis_img to a temp file so fpdf2 can embed it
        tmp_img = None
        if vis_img is not None:
            tmp_img = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
            cv2.imwrite(tmp_img.name, vis_img)
            tmp_img.close()
            
            # Scale image to fit page width (180mm max, with margins)
            h_img, w_img = vis_img.shape[:2]
            max_w_mm = 180
            scale = max_w_mm / w_img
            img_h_mm = h_img * scale
            
            # Cap height to avoid overflowing
            if img_h_mm > 120:
                img_h_mm = 120
                scale = img_h_mm / h_img
                max_w_mm = w_img * scale
            
            # Center the image
            x_offset = (210 - max_w_mm) / 2
            pdf.image(tmp_img.name, x=x_offset, y=pdf.get_y(), w=max_w_mm)
            pdf.ln(img_h_mm + 5)
        
        # ── Recommendation Badge ──
        doctor_yes = any(r["label"] == "Yes" for r in results_list) if results_list else False
        
        if doctor_yes:
            badge_color = UltrasoundReport.ERROR_ROSE
            badge_text = "RECOMMENDATION: CONSULT A DOCTOR"
        elif not results_list:
            badge_color = UltrasoundReport.SAGE_GREEN
            badge_text = "NO LESIONS DETECTED"
        else:
            badge_color = UltrasoundReport.SAGE_GREEN
            badge_text = "RECOMMENDATION: LOW RISK"
        
        # Draw colored badge bar
        pdf.set_fill_color(*badge_color)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 13)
        badge_y = pdf.get_y()
        pdf.rect(10, badge_y, 190, 12, 'F')
        pdf.set_xy(10, badge_y + 2)
        pdf.cell(190, 8, badge_text, align="C")
        pdf.ln(18)
        
        # ── Clinical Measurements Table ──
        if results_list:
            # Check if we need a new page
            if pdf.get_y() > 220:
                pdf.add_page()
            
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(*UltrasoundReport.DARK_TEXT)
            pdf.cell(0, 8, "Clinical Measurements", ln=True)
            
            pdf.set_draw_color(*UltrasoundReport.LAVENDER)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
            
            for rank, res in enumerate(results_list):
                if pdf.get_y() > 250:
                    pdf.add_page()
                
                # Lesion header
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(*UltrasoundReport.LAVENDER)
                pdf.cell(0, 7, f"Lesion #{rank + 1}", ln=True)
                
                # Table header
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_fill_color(240, 237, 245)  # Light lavender
                pdf.set_text_color(*UltrasoundReport.DARK_TEXT)
                
                col_w = [50, 45, 45, 50]
                headers = ["Metric", "Value", "Metric", "Value"]
                for i, (h, w) in enumerate(zip(headers, col_w)):
                    pdf.cell(w, 7, h, border=1, fill=True, align="C")
                pdf.ln()
                
                # Table data
                pdf.set_font("Helvetica", "", 9)
                
                circularity = res.get("circularity", 0.0)
                circ_lbl = "Smooth" if circularity >= 0.8 else ("Mod. irregular" if circularity >= 0.6 else "Irregular")
                p_val = f"{res['prob']:.2f}" if res.get("prob") is not None else "N/A"
                see_doc = res.get("label", "Unknown")
                
                rows = [
                    ("Height", f"{res['h_cm']:.2f} cm", "Width", f"{res['w_cm']:.2f} cm"),
                    ("H/W Ratio", f"{res['ratio']:.2f}", "Area", f"{res['area_cm2']:.2f} cm²"),
                    ("Boundary", f"{circ_lbl} ({circularity:.2f})", "Risk (p)", p_val),
                    ("See Doctor", see_doc, "", ""),
                ]
                
                for row in rows:
                    for i, (val, w) in enumerate(zip(row, col_w)):
                        # Bold for labels (even indices)
                        if i % 2 == 0:
                            pdf.set_font("Helvetica", "B", 9)
                            pdf.set_text_color(*UltrasoundReport.LIGHT_TEXT)
                        else:
                            pdf.set_font("Helvetica", "", 9)
                            # Color "Yes" in red
                            if val == "Yes":
                                pdf.set_text_color(*UltrasoundReport.ERROR_ROSE)
                            elif val == "No":
                                pdf.set_text_color(*UltrasoundReport.SAGE_GREEN)
                            else:
                                pdf.set_text_color(*UltrasoundReport.DARK_TEXT)
                        pdf.cell(w, 6, val, border=1, align="C" if i % 2 == 1 else "L")
                    pdf.ln()
                
                pdf.ln(5)
        
        # Save the PDF
        pdf.output(output_path)
        
        # Cleanup temp image
        if tmp_img and os.path.exists(tmp_img.name):
            os.unlink(tmp_img.name)
        
        return True, output_path
    
    except Exception as e:
        return False, str(e)
